---
- hosts: all
  become: true
  gather_facts: yes
  ignore_errors: true
  vars:
    user_name: serge2029
    group_name: devops
  vars_files:
    - variables.yml 
  tasks:
    - name: check the time
      command: datertrtgt
#      when: ansible_distribution == "jesse" or ansible_processor_nproc == 2

    - name: create user serge
      user:
         name: "{{user_name}}"
         comment: Serge Admin

    - name: create group
      group:
         name: "{{group_name}}"
         state: present

    - name: install package
      package:
         name: "{{pkg_name}}"
         state: present
