---
- hosts: db
  become: yes
  ignore_errors: yes
  gather_facts: 1
  vars:
    color: red
  tasks:
     - name: check number of cpu
       command: uptime
       register: uptime_output

     - name: Display the output 
       debug: 
        var: uptime_output.stdout

     - name: create file
       file: 
         path: /home/ec2-user/week3
         state: touch
         mode: '0644'
       register: file_output

     - name: display file output
       debug:
         var: color
